[FileDialog]
history=file:///home/sbs/Documents/daignostics/database recovery MDB/recovery/Issa-SSD_recovery_export, file:///home/sbs/Pictures, file:///home/sbs/Desktop, file:///home/sbs/Downloads/CoppeliaSim_Edu_V4_10_0_rev0_Ubuntu24_04/cadFiles/serialManipulator, file:///home/sbs, file:///home/sbs/Videos
lastVisited=file:///home/sbs/Videos
qtVersion=5.15.18
shortcuts=file:, file:///home/sbs
sidebarWidth=50
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
